# Generated by Django 5.1.15 on 2026-05-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['student__first_name', 'student__last_name'], 'verbose_name': 'Attendance yozuvi', 'verbose_name_plural': 'Attendance yozuvlari'},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Attendance session', 'verbose_name_plural': 'Attendance sessions'},
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Class schedule', 'verbose_name_plural': 'Class schedules'},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Reason for tardiness/absence, etc.'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Records cannot be modified after the session ends'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Which schedule it was generated from (during auto-generation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='attendance.classschedule'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='room',
            field=models.CharField(blank=True, default='', help_text='e.g. Room 301, Online', max_length=50),
        ),
    ]
