# Generated by Django 5.1.15 on 2026-05-10 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
        ('organizations', '0006_alter_organization_status_alter_plan_max_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='edited_count',
            field=models.PositiveSmallIntegerField(default=0, help_text="Bu yozuv necha marta o'zgartirilgan"),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='parent_notified',
            field=models.BooleanField(default=False, help_text='Telegram bot orqali ota-onaga xabar yuborilganmi'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='parent_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Set manually or 72h after session — marks become read-only', null=True),
        ),
        migrations.CreateModel(
            name='AttendanceEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('warning', 'Warning (3 absences)'), ('reprimand', 'Reprimand (5 absences)'), ('removal', 'Removal recommended (10 absences)')], max_length=16)),
                ('absence_count', models.PositiveSmallIntegerField(help_text='Triggered count (3, 5 yoki 10)')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_escalations', to='organizations.studentgroup')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_escalations_resolved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance escalation',
                'verbose_name_plural': 'Attendance escalations',
                'db_table': 'attendance_escalations',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['student', 'tier', 'resolved_at'], name='attendance__student_3612c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='Telegram chat ID (bot orqali olinadi)', max_length=32)),
                ('parent_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram binding',
                'verbose_name_plural': 'Telegram bindings',
                'db_table': 'attendance_telegram_bindings',
                'indexes': [models.Index(fields=['chat_id'], name='attendance__chat_id_a3e6ac_idx')],
                'unique_together': {('student', 'chat_id')},
            },
        ),
    ]
