# Generated by Django 5.1.15 on 2026-05-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_create_missing_escalation_telegram_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kechikdi'), ('excused', 'Sababli'), ('sick', 'Kasal')], db_index=True, max_length=20, null=True),
        ),
    ]
