# Generated by Django 5.1.15 on 2026-05-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('signup_source', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('admin', 'Admin')], default='email', max_length=10)),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('target_exam', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2C profile',
                'verbose_name_plural': 'B2C profiles',
            },
        ),
    ]
