# Generated by Django 5.1.15 on 2026-05-11 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cprofile',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2cprofile',
            name='target_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='b2cprofile',
            name='weekly_goal_sessions',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='B2CActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('full', 'Full Mock')], max_length=20)),
                ('minutes_spent', models.PositiveSmallIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('activity_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2C activity event',
                'verbose_name_plural': 'B2C activity events',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_date'], name='b2c_b2cacti_user_id_3f7107_idx')],
            },
        ),
    ]
