# Generated by Django 5.1.15 on 2026-05-12 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c', '0002_b2cprofile_exam_date_b2cprofile_target_band_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit balance',
                'verbose_name_plural': 'Credit balances',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signup_bonus', 'Ro‘yxatdan o‘tish bonusi'), ('admin_grant', 'Admin grant'), ('admin_deduct', 'Admin deduct'), ('purchase', 'Sotib olish'), ('spend', 'Test uchun foydalanish'), ('refund', 'Refund'), ('promo_code', 'Promo kod')], db_index=True, max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin grant uchun — kim qildi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit transaction',
                'verbose_name_plural': 'Credit transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='b2c_creditt_user_id_e70c91_idx')],
            },
        ),
    ]
