# Generated by Django 5.1.15 on 2026-04-27 21:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mock', '0003_mockparticipant_user'),
        ('organizations', '0004_seed_memberships_from_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'To‘lanmagan'), ('paid', 'To‘langan'), ('overdue', 'Muddati o‘tgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_billing_cycles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='organizations.organization')),
            ],
            options={
                'db_table': 'billing_cycles',
                'ordering': ['-period_start'],
                'unique_together': {('organization', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_session_tier_1', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), help_text='0–100 sessiya: bitta sessiya narxi (so‘m)', max_digits=10)),
                ('price_per_session_tier_2', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='101–500 sessiya: bitta sessiya narxi', max_digits=10)),
                ('price_per_session_tier_3', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='501+ sessiya: bitta sessiya narxi', max_digits=10)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('payment_period', models.CharField(choices=[('monthly', 'Oylik'), ('quarterly', 'Kvartal'), ('annual', 'Yillik')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tier', to='organizations.organization')),
            ],
            options={
                'db_table': 'pricing_tiers',
            },
        ),
        migrations.CreateModel(
            name='SessionBillingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=10)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('is_billed', models.BooleanField(default=False)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='billing.billingcycle')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_log', to='mock.mocksession')),
            ],
            options={
                'db_table': 'session_billing_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
