# Generated by Django 5.1.15 on 2026-05-02 13:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('mock', '0006_mockparticipant_speaking_audio_and_more'),
        ('organizations', '0005_studentgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockSessionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('30000.00'), max_digits=10)),
                ('is_charged', models.BooleanField(default=True, help_text="False — bepul/test sessiya, billing'da hisoblanmaydi")),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mock_session_charges',
                'ordering': ['-charged_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('bank_transfer', 'Bank o‘tkazmasi'), ('card', 'Karta'), ('other', 'Boshqa')], max_length=20)),
                ('payment_date', models.DateField()),
                ('receipt_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'lov tarixi",
                'verbose_name_plural': "To'lov tarixi",
                'db_table': 'payment_history',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='billingcycle',
            options={'ordering': ['-year', '-month', '-period_start']},
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='month',
            field=models.IntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='total_students',
            field=models.PositiveIntegerField(default=0, help_text='Charge qilingan unique talabalar soni'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('bank_transfer', 'Bank o‘tkazmasi'), ('card', 'Karta'), ('other', 'Boshqa'), ('', '—')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Bu davrda yakunlangan mock sessiyalar (charge yaratilgan)'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['organization', 'status'], name='billing_cyc_organiz_4d9086_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['year', 'month'], name='billing_cyc_year_420181_idx'),
        ),
        migrations.AddField(
            model_name='mocksessioncharge',
            name='billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_charges', to='billing.billingcycle'),
        ),
        migrations.AddField(
            model_name='mocksessioncharge',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_charges', to='mock.mockparticipant'),
        ),
        migrations.AddField(
            model_name='mocksessioncharge',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_charges', to='mock.mocksession'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='billing_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billingcycle'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mocksessioncharge',
            index=models.Index(fields=['billing_cycle', 'is_charged'], name='mock_sessio_billing_277972_idx'),
        ),
        migrations.AddIndex(
            model_name='mocksessioncharge',
            index=models.Index(fields=['session', 'participant'], name='mock_sessio_session_4e552d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mocksessioncharge',
            unique_together={('session', 'participant')},
        ),
    ]
