# Generated by Django 5.1.15 on 2026-05-02 13:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_mocksessioncharge_paymenthistory_and_more'),
        ('organizations', '0005_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('pay_per_test', 'Pay Per Test'), ('starter', 'Center Starter'), ('pro', 'Center Pro'), ('enterprise', 'Enterprise')], default='pay_per_test', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Oylik obuna narxi (pay_per_test uchun 0)', max_digits=12)),
                ('monthly_quota', models.PositiveIntegerField(blank=True, help_text='Oyda nechta mock test (NULL = cheksiz)', null=True)),
                ('pay_per_test_threshold', models.PositiveIntegerField(default=100, help_text='Progressiv narx chegarasi (umumiy hisoblangan testlar)')),
                ('pay_per_test_first_price', models.DecimalField(decimal_places=2, default=Decimal('30000.00'), help_text='Threshold ichidagi har test narxi', max_digits=10)),
                ('pay_per_test_after_price', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Threshold dan keyingi har test narxi', max_digits=10)),
                ('starts_at', models.DateField(default=django.utils.timezone.now)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_tier', to='organizations.organization')),
            ],
            options={
                'db_table': 'subscription_tiers',
            },
        ),
    ]
