# Generated by Django 5.1.15 on 2026-05-08 05:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_etap22_pricing_30k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='status',
            field=models.CharField(choices=[('pending', 'To‘lanmagan'), ('paid', 'To‘langan'), ('overdue', 'Muddati o‘tgan'), ('cancelled', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Mock sessions completed in this period (charges generated)'),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='total_students',
            field=models.PositiveIntegerField(default=0, help_text='Number of unique students charged'),
        ),
        migrations.AlterField(
            model_name='mocksessioncharge',
            name='is_charged',
            field=models.BooleanField(default=True, help_text='False — free/test session, not counted in billing'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='price_per_session_tier_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000.00'), help_text='0–100 sessions: price per session (UZS)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='price_per_session_tier_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='101–500 sessions: price per session', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='price_per_session_tier_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='501+ sessions: price per session', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monthly subscription price (0 for pay_per_test)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='monthly_quota',
            field=models.PositiveIntegerField(blank=True, help_text='How many mock tests per month (NULL = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='pay_per_test_after_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Per-test price above the threshold', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='pay_per_test_first_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000.00'), help_text='Per-test price under the threshold', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='pay_per_test_threshold',
            field=models.PositiveIntegerField(default=100, help_text='Progressive pricing threshold (total billed tests)'),
        ),
    ]
