# Generated by Django 5.1.15 on 2026-04-27 19:59

import apps.mock.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_seed_memberships_from_users'),
        ('tests', '0003_passage_instructions_passage_subtitle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('listening_duration', models.PositiveIntegerField(default=30)),
                ('reading_duration', models.PositiveIntegerField(default=60)),
                ('writing_duration', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('finished', 'Tugagan')], default='waiting', max_length=20)),
                ('section_started_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.CharField(default=apps.mock.models.generate_access_code, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mock_sessions', to=settings.AUTH_USER_MODEL)),
                ('listening_test', models.ForeignKey(blank=True, limit_choices_to={'module': 'listening'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.test')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_sessions', to='organizations.organization')),
                ('reading_test', models.ForeignKey(blank=True, limit_choices_to={'module': 'reading'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.test')),
                ('writing_test', models.ForeignKey(blank=True, limit_choices_to={'module': 'writing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.test')),
            ],
            options={
                'db_table': 'mock_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='mock.mocksession')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_state_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MockParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('browser_session_id', models.CharField(default=apps.mock.models.generate_browser_session_id, max_length=64, unique=True)),
                ('listening_answers', models.JSONField(blank=True, default=dict)),
                ('reading_answers', models.JSONField(blank=True, default=dict)),
                ('writing_task1_text', models.TextField(blank=True, default='')),
                ('writing_task2_text', models.TextField(blank=True, default='')),
                ('listening_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('listening_correct', models.PositiveIntegerField(blank=True, null=True)),
                ('listening_total', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reading_correct', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_total', models.PositiveIntegerField(blank=True, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('listening_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reading_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('writing_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mock.mocksession')),
            ],
            options={
                'db_table': 'mock_participants',
                'ordering': ['joined_at'],
                'unique_together': {('session', 'full_name')},
            },
        ),
    ]
