# Generated by Django 5.1.15 on 2026-04-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockparticipant',
            name='overall_band_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='IELTS Overall: (L+R+W+S)/4, 0.5 stepda yaxlitlanadi', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_speaking_gradings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('graded', 'Baholangan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_writing_gradings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('grading', 'Baholanyapti'), ('graded', 'Baholangan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task1_coherence',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 1: Coherence and Cohesion (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task1_grammar',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 1: Grammatical Range and Accuracy (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task1_lexical',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 1: Lexical Resource (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task1_task_achievement',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 1: Task Achievement (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task2_coherence',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 2: Coherence and Cohesion (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task2_grammar',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 2: Grammatical Range and Accuracy (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task2_lexical',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 2: Lexical Resource (0–9)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_task2_task_response',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Task 2: Task Response (0–9)', max_digits=3, null=True),
        ),
    ]
