# Generated by Django 5.1.15 on 2026-04-27 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0002_mockparticipant_overall_band_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockparticipant',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Login qilingan talaba bo'lsa unga link", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
