# Generated by Django 5.1.15 on 2026-05-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0005_speaking_criteria'),
        ('tests', '0006_test_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_audio',
            field=models.FileField(blank=True, help_text='Talaba yozib olgan speaking audio (webm/mp3/m4a)', null=True, upload_to='speaking_recordings/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='speaking_duration',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='speaking_test',
            field=models.ForeignKey(blank=True, help_text="Speaking test (ixtiyoriy — mavjud bo'lsa speaking bosqichi qo'shiladi)", limit_choices_to={'module': 'speaking'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='mocksession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Kutilmoqda'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('finished', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='waiting', max_length=20),
        ),
    ]
