# Generated by Django 5.1.15 on 2026-05-02 18:56

import apps.mock.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0007_etap19_pre_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='ORG-YYYY-MM-NNN formatida (e.g. ILDIZ-2026-05-001)', max_length=50, unique=True)),
                ('verification_code', models.CharField(default=apps.mock.models.generate_verification_code, help_text='QR/URL orqali tekshirish uchun token', max_length=64, unique=True)),
                ('listening_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reading_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('writing_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('speaking_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('overall_band_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('full_name', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True, default='')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(help_text='Sertifikat berilgan mock participant', on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='mock.mockparticipant')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_certificates',
                'ordering': ['-issue_date', '-id'],
                'indexes': [models.Index(fields=['certificate_number'], name='mock_certif_certifi_d4d76e_idx'), models.Index(fields=['verification_code'], name='mock_certif_verific_554e8c_idx')],
            },
        ),
    ]
