# Generated by Django 5.1.15 on 2026-05-04 08:37

import apps.mock.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0008_certificate'),
        ('tests', '0008_alter_listeningpart_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mocksession',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(help_text='Format: ORG-YYYY-MM-NNN (e.g. ILDIZ-2026-05-001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='participant',
            field=models.OneToOneField(help_text='Mock participant the certificate was issued to', on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='mock.mockparticipant'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(default=apps.mock.models.generate_verification_code, help_text='Token for verification via QR or URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='mockparticipant',
            name='overall_band_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='IELTS Overall: (L+R+W+S)/4, rounded to 0.5', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='mockparticipant',
            name='speaking_audio',
            field=models.FileField(blank=True, help_text='Speaking audio recorded by the student (webm/mp3/m4a)', null=True, upload_to='speaking_recordings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mockparticipant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Direct link if the student is logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mocksession',
            name='allow_guests',
            field=models.BooleanField(default=True, help_text='Whether students not on the roster can join by entering their name'),
        ),
        migrations.AlterField(
            model_name='mocksession',
            name='allow_late_join',
            field=models.BooleanField(default=True, help_text='Allow joining after the session starts'),
        ),
        migrations.AlterField(
            model_name='mocksession',
            name='link_expires_at',
            field=models.DateTimeField(blank=True, help_text='Link expiration time (empty = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='mocksession',
            name='speaking_test',
            field=models.ForeignKey(blank=True, help_text='Speaking test (optional — adds the speaking stage if present)', limit_choices_to={'module': 'speaking'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='mocksession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Kutilmoqda'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('finished', 'Tugagan'), ('cancelled', 'Revoked')], default='waiting', max_length=20),
        ),
    ]
