# Generated by Django 5.1.15 on 2026-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0013_mockparticipant_audio_finished_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockparticipant',
            name='audio_played_parts',
            field=models.JSONField(blank=True, default=list, help_text='List of part orders whose audio has STARTED (click): [1, 2, ...]'),
        ),
    ]
