# Generated by Django 5.1.15 on 2026-05-12 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0014_alter_mockparticipant_audio_played_parts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockparticipant',
            name='exam_taker_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_speaking_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_override_band',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Admin override (speaking) — asl bahoga ustunlik', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='speaking_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_writing_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_override_band',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Admin override (writing) — asl bahoga ustunlik', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mockparticipant',
            name='writing_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
