# Generated by Django 5.1.15 on 2026-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0016_backfill_exam_taker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocksession',
            name='is_official_exam',
            field=models.BooleanField(db_index=True, default=False, help_text="Rasmiy mock imtihon — talabaga natija ko'rinmaydi"),
        ),
    ]
