# Generated by Django 5.1.15 on 2026-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_group_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('org_admin', 'Center Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('b2c_user', 'Individual (B2C)')], default='student', max_length=20),
        ),
    ]
