# Generated by Django 5.1.15 on 2026-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='essay_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
