# Generated by Django 5.1.15 on 2026-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_attempt_created_at_started_at_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='section_band_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='speaking_recordings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
