# Generated by Django 5.1.15 on 2026-05-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_attempt_section_band_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='auto_submit_reason',
            field=models.CharField(blank=True, default='', help_text='too_many_violations | time_expired | manual', max_length=64),
        ),
        migrations.AddField(
            model_name='attempt',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text='Tizim avtomatik submit qilganmi (violations / time / manual)'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='flagged_as_cheating',
            field=models.BooleanField(default=False, help_text="Strict mode violation thresholdi kesib o'tilganda True"),
        ),
        migrations.CreateModel(
            name='TestSecurityViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tab_switched', 'Tab switched'), ('window_blurred', 'Window lost focus'), ('fullscreen_exited', 'Fullscreen exited'), ('devtools_attempt', 'DevTools shortcut attempted'), ('copy_attempt', 'Copy attempted'), ('paste_attempt', 'Paste attempted'), ('print_attempt', 'Print attempted'), ('save_attempt', 'Save attempted'), ('right_click', 'Right-click attempted'), ('view_source', 'View source attempted'), ('select_all', 'Select-all attempted'), ('other', 'Other')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text="tab_switched / window_blurred uchun: talaba qancha vaqt yo'q bo'lganligi", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Qo'shimcha context: user_agent, viewport, va h.k.")),
                ('counted', models.BooleanField(default=True, help_text="False = forgiven (debounced kichik blur). Auto-submit'ga ta'sir qilmaydi.")),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='attempts.attempt')),
            ],
            options={
                'ordering': ['attempt', 'occurred_at'],
                'indexes': [models.Index(fields=['attempt', 'type'], name='attempts_te_attempt_9ae96f_idx'), models.Index(fields=['occurred_at'], name='attempts_te_occurre_f7ade4_idx')],
            },
        ),
    ]
