# Generated by Django 5.1.15 on 2026-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0006_attempt_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='guest_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
