#!/usr/bin/env python3
"""Apply Uzbek -> English replacements across frontend src and backend apps.

Two-phase approach:
  Phase A: literal substring replacement of multi-word phrases (longest first).
  Phase B: regex word-boundary replacement of single Uzbek labels — these
           must NOT match when they appear inside a longer Uzbek inflection
           (e.g. "Talaba" must not match inside "Talabalar").

Each Uzbek source string is expanded to ASCII / curly / backslash-escaped
apostrophe variants automatically.

Run from repo root:
    python3 scripts/translate_uzbek.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "frontend" / "src"
BACKEND = ROOT / "backend" / "apps"

APOSTROPHES = ["'", "’", "‘", "ʻ"]


def variants(uz: str) -> list[str]:
    out = {uz}
    if "'" in uz:
        for glyph in APOSTROPHES:
            out.add(uz.replace("'", glyph))
        out.add(uz.replace("'", "\\'"))
    return sorted(out, key=len, reverse=True)


# ── Phase A: multi-word literal replacements ─────────────────────────────
PHRASES: list[tuple[str, str]] = [
    # Long instructional sentences
    ("Bir sahifada section/passage va savollarni qo'shing — oxirida bir martalik saqlanadi",
     "Add sections/passages and questions on one page — saved atomically at the end"),
    ("Section/passage va savollarni o'zgartiring — saqlash bosilganda atomar yangilanadi",
     "Edit sections/passages and questions — applied atomically when you press Save"),
    ("Markaz uchun birinchi ustozni qo'shing — talabalar tayinlash mumkin bo'ladi.",
     "Add the first teacher for the center — you'll then be able to assign students."),
    ("Markazga ro'yxatdan o'tgan barcha talabalar",
     "All students registered in the center"),
    ("Markazda ishlaydigan ustozlar va ularning faolligi",
     "Teachers working at the center and their activity"),
    ("Talabalar guruhini yarating va o'qituvchini biriktiring",
     "Create a student group and assign a teacher"),
    ("Haftalik dars kunlari va vaqtlari. Generate Sessions buyrug'i shu jadval asosida sessiya yaratadi.",
     "Weekly class days and times. The Generate Sessions command creates sessions based on this schedule."),
    ("Faol guruhlarning o'rtacha balli bo'yicha reytingi",
     "Ranking of active groups by average score"),
    ("Avval bir nechta guruh yarating va talabalarni biriktiring.",
     "First create a few groups and assign students."),
    ("Cambridge IELTS yoki o'xshash PDF dan savollarni avtomatik chiqaring",
     "Automatically extract questions from Cambridge IELTS or similar PDFs"),
    ("“Yangi talaba” tugmasini bosib birinchi talabani qo'shing.",
     "Click the “New Student” button to add the first student."),
    ("Yana bir bor: barcha savollar va urinishlar ham o'chiriladi. Tasdiqlaysizmi?",
     "Once more: all questions and attempts will also be deleted. Are you sure?"),
    ("SuperAdmin tayyorlagan, hamma markazlar nusxalashi mumkin bo'lgan testlar",
     "Tests prepared by SuperAdmin that any center can clone"),
    ("Barcha 4 ta plan kodi (trial/starter/pro/enterprise) band. Mavjud planni tahrirlang.",
     "All 4 plan codes (trial/starter/pro/enterprise) are taken. Edit an existing plan."),
    ("Test fullscreen rejimida bajarilishi kerak — qayta to'liq ekranga o'tkazildi.",
     "The test must run in fullscreen — switched back to fullscreen."),
    ("Ekranni kichraytirish (favqulodda holat uchun)",
     "Minimize screen (for emergencies)"),
    ("Test boshlashda xatolik. Qayta urinib ko'ring.",
     "Failed to start the test. Please try again."),
    ("⚠️ Testdan chiqmang! Bu birinchi ogohlantirish.",
     "⚠️ Don't leave the test! This is your first warning."),
    ("Tavsiyalar, e'tibor berilishi kerak bo'lgan jihatlar…",
     "Recommendations, points that need attention…"),
    ("Test/markaz nomi bo'yicha qidirish…", "Search by test or center name…"),
    ("IELTS Listening — qism va savollarni qo'shing",
     "IELTS Listening — add parts and questions"),
    ("IELTS Reading — passage va savollarni qo'shing",
     "IELTS Reading — add passages and questions"),
    ("Talabalar reytingi (davomat bo'yicha)", "Student ranking (by attendance)"),
    ("Talaba topilmadi yoki ruxsat yo'q.", "Student not found or access denied."),
    ("Test topilmadi yoki sizga ruxsat yo'q.", "Test not found or access denied."),
    ("Server xatoligi (500). Adminga xabar bering.",
     "Server error (500). Please contact the admin."),
    ("Talabalar davomati (tez orada)", "Student attendance (coming soon)"),
    ("Bu funksiya keyingi etap'da yakunlanadi",
     "This feature will be finalized in the next stage"),
    ("Audio yuklang, savollar yarating", "Upload audio, create questions"),
    ("Har savolga to'g'ri javob ko'rsating",
     "Provide the correct answer for every question"),
    ("Task 1 va Task 2 sharti kiritilishi kerak",
     "Task 1 and Task 2 prompts must be entered"),
    ("Har section'ga sarlavha bering", "Give each section a title"),
    ("Testni yuklashda xato — orqaga qayting",
     "Failed to load the test — please go back"),
    ("Practice testni boshlashda xatolik", "Failed to start the practice test"),
    ("Audio yuklab bo'lmadi — internetingizni tekshirib qayta urinib ko'ring.",
     "Couldn't load audio — please check your internet and try again."),
    ("Listening test'da audio fayl topilmadi.",
     "No audio file found in the Listening test."),
    ("Part 1 to'liq yuklandi. Test boshlanganda timer ham ishga tushadi.",
     "Part 1 fully loaded. The timer starts when the test begins."),
    ("Birinchi qism to'liq yuklab olinadi, keyin test boshlanadi. ",
     "The first part is fully downloaded, then the test starts. "),
    ("Quyida har savol uchun darhol javoblar ko'rsatildi. Cheklov",
     "Answers for each question are shown below. Limit"),
    ("Yuborilgandan keyin o'zgartirib bo'lmaydi. Ustoz qo'lda baholaydi.",
     "After submission you can't edit. The teacher will grade manually."),
    ("Sertifikat topilmadi", "Certificate not found"),
    ("Verifikatsiya kodi noto'g'ri yoki sertifikat mavjud emas.",
     "Verification code is invalid or the certificate doesn't exist."),
    ("Bu sertifikat bekor qilingan — hozirda haqiqiy hisoblanmaydi.",
     "This certificate has been revoked — it is no longer valid."),
    ("Bekor qilingan: ", "Revoked: "),
    ("Bekor qilingan", "Revoked"),
    ("Markaz natijalari, trend va eng yaxshi talabalar.",
     "Center results, trends, and top students."),
    ("Top 10 talabalar", "Top 10 students"),
    ("6 oylik trend", "6-month trend"),
    ("Oxirgi sessiyalar", "Recent sessions"),
    ("Bugungi davomat", "Today's attendance"),
    ("Davomat yuklanmadi.", "Attendance failed to load."),
    ("Davomat hali olinmagan", "Attendance not taken yet"),
    ("Bu guruhda talaba yo'q yoki hali sessiya yaratilmagan.",
     "There are no students in this group or sessions haven't been created yet."),
    ("Talabalar guruhlari", "Student groups"),
    ("Hozircha mock sessiyalar yo'q.", "No mock sessions yet."),
    ("Markaz sozlamalari", "Center settings"),
    ("Markaz brendi (logo, rang) va aloqa ma'lumotlari.",
     "Center branding (logo, color) and contact information."),
    ("Sozlamalarni yuklab bo'lmadi.", "Couldn't load settings."),
    ("Tugmalar va talaba sahifasidagi accent rangi",
     "Accent color for buttons and the student page"),
    ("Yangisini yuklash uchun pastga drag qiling yoki “Almashtirish”ni bosing.",
     "Drag a new one below or click “Replace”."),
    ("Faylni bu yerga tashlang yoki ", "Drop the file here or "),
    ("Bu testdan nusxa yaratamizmi?", "Clone this test?"),
    ("Hali testingiz yo'q. Global katalogdan klon qiling.",
     "You don't have any tests yet. Clone one from the global catalog."),
    ("Katalogda hali test yo'q.", "No tests in the catalog yet."),
    ("Markaz bazasidagi testlar va SuperAdmin tayyorlagan global katalog",
     "Tests in the center's database and the global catalog prepared by SuperAdmin"),
    ("Avval markazni tanlang (Centers ro'yxatidan).",
     "First select a center (from the Centers list)."),
    ("Avval markazni tanlang.", "First select a center."),
    ("Yangi test yaratish va savollarni qo'shish uchun \"Yangi test\" tugmasini bosing.",
     'Click the "New test" button to create a new test and add questions.'),
    ("Test natijalarini ko'rish uchun har bir qatordagi \"Natijalar\" linkidan foydalaning.",
     'Use the "Results" link in each row to view test results.'),
    ("Sertifikatlarni yuklab bo'lmadi.", "Couldn't load certificates."),
    ("Hali sertifikat yo'q", "No certificates yet"),
    ("Baholash jarayonida — barcha sectionlar yakunlanishi",
     "Grading in progress — all sections must be completed"),
    ("Sertifikatni yuklab olish", "Download certificate"),
    ("Tarixni yuklab bo'lmadi.", "Couldn't load history."),
    ("Hali practice qilmadingiz.", "You haven't practiced yet."),
    ("darhol natijani va to'g'ri javoblarni ko'ring.",
     "see the result and correct answers immediately."),
    ("Hali biron-bir mashq yo'q. Yuqoridagi modullardan boshlang.",
     "No exercises yet. Start with one of the modules above."),
    ("Testlarni yuklab bo'lmadi.", "Couldn't load tests."),
    ("Audio fayllar yuklab bo'lmadi.", "Couldn't load audio files."),
    ("Audio fayllar topilmadi.", "No audio files found."),
    ("Markazlar bo'yicha sessiya-asosli hisob-kitob va to'lovlar.",
     "Per-center session-based billing and payments."),
    ("Ma'lumotlarni yuklab bo'lmadi.", "Couldn't load data."),
    ("Hisob-kitob davriga kirmagan sessiyalar",
     "Sessions not yet included in a billing cycle"),
    ("Hisob-kitob davrlari", "Billing cycles"),
    ("Bitta sessiya narxi (so'mda). Avtomatik tier session soniga qarab tanlanadi.",
     "Price per session (in UZS). Tier is selected automatically based on session count."),
    ("Bitta sessiya narxi (so'mda).", "Price per session (in UZS)."),
    ("Yaqin orada tarif tugaydigan markaz yo'q.",
     "No centers with plans expiring soon."),
    ("Platforma bo'yicha umumiy ko'rsatkichlar.",
     "Platform-wide overview metrics."),
    ("Statistika yuklab bo'lmadi.", "Couldn't load statistics."),
    ("Plans yuklab bo'lmadi.", "Couldn't load plans."),
    ("Platforma tariflari (Plans). Markaz yaratganda tanlanadi.",
     "Platform plans. Selected when creating a center."),
    ("Talabalar topshirgan Writing matnlarini 8 ta criteria bo'yicha baholang.",
     "Grade students' Writing submissions across 8 criteria."),
    ("Baholash uchun Writing yo'q", "No Writing to grade"),
    ("Barcha topshirilgan Writing'lar baholangan.",
     "All submitted Writing has been graded."),
    ("almashganingizda audio davom etaveradi.",
     "the audio keeps playing while you switch."),
    ("mikrofonga aytib bering. Tugatgach ", "speak into the microphone. When done, press "),
    ("Ustoz baholashni kutmoqdasiz.", "Waiting for the teacher's grading."),
    ("Saqlashda xatolik yuz berdi", "Save failed"),
    ("Bekor qilish sababi (ixtiyoriy):", "Cancellation reason (optional):"),
    ("Hisoblangan Writing band", "Calculated Writing band"),
    ("Hisob-kitob davri yaratildi", "Billing cycle created"),
    ("O'tgan oyga cycle yaratish", "Create cycle for last month"),
    ("Talabani o'chirmoqchimisiz?", "Delete this student?"),
    ("Ustozni o'chirmoqchimisiz?", "Delete this teacher?"),
    ("Talabani guruhdan chiqarmoqchimisiz?", "Remove this student from the group?"),
    ("Guruhni o'chirmoqchimisiz? Talabalar guruhsiz qoladi.",
     "Delete this group? Students will be left without a group."),
    ("Ism yoki login bo'yicha qidirish...", "Search by name or login..."),
    ("Test nomi yoki kategoriya...", "Test name or category..."),
    ("Talaba yoki test nomi...", "Student or test name..."),
    ("Xususiyatlar (har qatorda bittadan)", "Features (one per line)"),
    ("Cycle yaratishda xatolik", "Failed to create cycle"),
    ("Narxlarni saqlashda xatolik", "Failed to save prices"),
    ("Audio yuklashda xatolik", "Failed to upload audio"),
    ("Rasm yuklashda xatolik", "Failed to upload image"),
    ("Test boshlashda xatolik", "Failed to start the test"),
    ("0–9 oralig'ida son kiriting", "Enter a number between 0 and 9"),
    ("Talabalar topilmadi.", "No students found."),
    ("O'qituvchi topilmadi.", "Teacher not found."),
    ("Test topilmadi.", "Test not found."),
    ("Sessiya topilmadi.", "Session not found."),
    ("Audio fayl yuklang (MP3, M4A — 50 MB gacha)",
     "Upload an audio file (MP3, M4A — up to 50 MB)"),
    ("Fayl 50 MB dan kichik bo'lsin", "File must be smaller than 50 MB"),
    ("PDF faylni yuklang", "Upload the PDF file"),
    ("PDF faylni tanlang yoki bu yerga sudrab tashlang",
     "Choose a PDF file or drag it here"),
    ("Audio yuklash va testni saqlash bosqichi keyingi etap'da to'liq",
     "Audio upload and test save will be completed in the next stage"),
    ("Saqlash (tez orada)", "Save (coming soon)"),
    ("Bu qismda savol topilmadi.", "No questions found in this part."),
    ("Hali savol qo'shilmagan", "No questions added yet"),
    ("To'liq baholash (kriteriyalar + feedback)",
     "Full grading (criteria + feedback)"),
    ("To'liq baholash (kriteriyalar + audio)", "Full grading (criteria + audio)"),
    ("Bu sessiyada talaba bo'lmagan.", "No students in this session."),
    ("Avval barcha modullarni baholang", "First grade all modules"),
    ("Avval barcha 4 modulni baholang.", "First grade all 4 modules."),
    ("Sessiya yakunlandi", "Session ended"),
    ("Sessiya qayta ochildi", "Session reopened"),
    ("Talaba qidirish…", "Search student…"),
    ("Guruh yoki o'qituvchi nomi…", "Group or teacher name…"),
    ("Guruhda talaba yo'q", "No students in the group"),
    ("Faqat hech qaysi guruhga biriktirilmagan talabalar ko'rinadi.",
     "Only students not assigned to any group are shown."),
    ("Mos talaba topilmadi", "No matching students"),
    ("Hech narsa tanlanmadi", "Nothing selected"),
    ("Qidiruv bo'yicha hech narsa topilmadi.", "Nothing matched the search."),
    ("Talabani tahrirlash", "Edit student"),
    ("Pastdagi tugmani bossangiz, test markazlar uchun katalogga chiqadi.",
     "Pressing the button below publishes the test to the centers' catalog."),
    ("Eslab qolish yoki nusxa olish uchun yuqoridagi tugmalardan",
     "Use the buttons above to remember or copy"),
    ("ko'rsatiladi.", "shown."),
    ("📋 PREVIEW MODE — bu admin uchun ko'rinish, javoblar yashil rangda ko'rinadi",
     "📋 PREVIEW MODE — admin view, correct answers shown in green"),
    ("Sarlavhalar ro'yxati (List of Headings) — to'g'ri sarlavhani tanlang:",
     "List of headings — pick the correct heading:"),
    ("Variantlar (har qatorda bittadan), to'g'ri javobni tanlang:",
     "Options (one per line), select the correct answer:"),
    ("Yana ${requiredQuestions - totalQuestions} ta savol qo'shing",
     "Add ${requiredQuestions - totalQuestions} more question(s)"),
    ("Mock sessiyada faqat <b>published</b> testlar ko'rinadi",
     "Only <b>published</b> tests appear in mock sessions"),
    ("Darhol e'lon qilish", "Publish immediately"),
    ("Chart / rasm (Task 1 uchun)", "Chart / image (for Task 1)"),
    ("IELTS Task 1 uchun chart, grafik yoki jadval (PNG/JPG/WEBP).",
     "Chart, graph, or table for IELTS Task 1 (PNG/JPG/WEBP)."),
    ("Bu turdagi savol uchun maxsus editor keyingi etapda qo'shiladi.",
     "A dedicated editor for this question type will be added in the next stage."),
    ("Yangi savol turi", "New question type"),
    ("Writing testlar uchun savollar yo'q. Talaba essay yozadi va qo'lda",
     "No questions for Writing tests. The student writes an essay and is graded manually"),
    ("Chart rasm yuklash UI keyingi etapda — hozir API tayyor:",
     "Chart image upload UI is in the next stage — API is ready:"),
    ("Test turini tanlang", "Choose test type"),

    # Template-literal fragments
    (" talaba`", " students`"),
    (" sessiya`", " sessions`"),
    (" ustoz`", " teachers`"),
    (" tugatilgan`", " completed`"),
    (" markazi talabalari", " center students"),
    (" markazi statistikasi", " center statistics"),
    (" markazi o'qituvchilari", " center teachers"),
    (" markazi yozma ishlari", " center writings"),
    (" — testlar boshqaruvi", " — tests management"),
    (" — Davomat hisoboti", " — Attendance Report"),
    (" — Dars jadvali", " — Class schedule"),
    ("Oxirgi 7 kun: ", "Last 7 days: "),
    ("Yuklanmoqda… ${progress}%", "Loading… ${progress}%"),
    ("Hozir: ${sections.length} part, ${totalQuestions} savol. ",
     "Currently: ${sections.length} parts, ${totalQuestions} questions. "),
    ("Hozir: ${sections.length} passage, ${totalQuestions} savol. ",
     "Currently: ${sections.length} passages, ${totalQuestions} questions. "),
    ("Listening test 4 part va aynan 40 savoldan iborat bo'lishi kerak. ",
     "A Listening test must contain 4 parts and exactly 40 questions. "),
    ("Reading test 3 passage va aynan 40 savoldan iborat bo'lishi kerak. ",
     "A Reading test must contain 3 passages and exactly 40 questions. "),
    ("${r.group.student_count} talaba · ${r.sessions_count} sessiya",
     "${r.group.student_count} students · ${r.sessions_count} sessions"),
    ("${selected.size} ta talaba qo'shildi", "${selected.size} students added"),
    ("${totals.unbilled_sessions} ta hali billing'sa kiritilmagan",
     "${totals.unbilled_sessions} not yet included in billing"),
    ("Jami daromad: ", "Total revenue: "),
    ("Jami: ${data.attempts_total}", "Total: ${data.attempts_total}"),
    ("${p.full_name} uchun rasmiy sertifikat berasizmi?",
     "Issue an official certificate for ${p.full_name}?"),
    ("${p.full_name} sertifikatini bekor qilasizmi?",
     "Revoke ${p.full_name}'s certificate?"),
    ("${target} → hozir ${avg?.toFixed(1) ?? '—'}",
     "${target} → now ${avg?.toFixed(1) ?? '—'}"),
    ("${c.label} 0–9 oralig'ida bo'lsin.",
     "${c.label} must be between 0 and 9."),
    ('"${name}" doimiy o\'chiriladi! Bu amalni qaytarib bo\'lmaydi. Davom etamizmi?',
     '"${name}" will be permanently deleted! This cannot be undone. Continue?'),
    ('"${name}" testini draft holatiga qaytarasizmi? Talabalar uchun ko\'rinmaydi.',
     'Move "${name}" back to draft? It will be hidden from students.'),
    ('"${name}" testini nashr qilasizmi? Talabalar uchun ko\'rinadigan bo\'ladi.',
     'Publish "${name}"? Students will be able to see it.'),
    ("(${need - wc} kerak)", "(${need - wc} needed)"),
    ("Jami: <strong>{totalWords}</strong> so'z",
     "Total: <strong>{totalWords}</strong> words"),
    ("{wordCount(detail.writing_task1_text)} so'z",
     "{wordCount(detail.writing_task1_text)} words"),
    ("{wordCount(detail.writing_task2_text)} so'z",
     "{wordCount(detail.writing_task2_text)} words"),
    ("{wc} / {need} so'z", "{wc} / {need} words"),
    ("ILDIZmock — Yangi guruh", "ILDIZmock — New group"),
    ("ILDIZmock — Test tahrirlash", "ILDIZmock — Edit test"),
    ("ILDIZmock — Yangi test ", "ILDIZmock — New test "),

    # Confirms / toasts / error messages / labels
    ("Test arxivdan qaytarildi.", "Test restored from archive."),
    ("Test draft holatiga qaytarildi.", "Test moved back to draft."),
    ("Sertifikatni bekor qilish", "Revoke certificate"),
    ("Sertifikat yuklanmadi", "Certificate failed to load"),
    ("Saqlash va parol olish", "Save and get password"),
    ("Saqlash va davom →", "Save and continue →"),
    ("Doimiy o'chirish", "Permanently delete"),
    ("Test topilmadi (404).", "Test not found (404)."),
    ("Talaba topilmadi.", "Student not found."),
    ("Talaba topilmadi", "Student not found"),
    ("Ma'lumot yetarli emas", "Not enough data"),
    ("Ma'lumot yo'q", "No data"),
    ("Ma'lumot olib bo'lmadi.", "Couldn't fetch data."),
    ("Hali talaba yo'q", "No students yet"),
    ("Hali ustoz qo'shilmagan", "No teachers added yet"),
    ("Hozircha guruh yo'q", "No groups yet"),
    ("Hali guruh yo'q", "No groups yet"),
    ("Hali jadval yo'q", "No schedule yet"),
    ("Hali test yo'q.", "No tests yet."),
    ("Hozircha sessiya yo'q", "No sessions yet"),
    ("Guruh topilmadi", "Group not found"),
    ("Guruhlar taqqoslash", "Compare groups"),
    ("Guruh nomini kiriting", "Enter the group name"),
    ("Guruh yaratildi", "Group created"),
    ("Guruh o'chirildi", "Group deleted"),
    ("Yangi guruh", "New group"),
    ("Yangi test yaratish", "Create new test"),
    ("Test nomini kiriting", "Enter the test name"),
    ("Test yaratildi", "Test created"),
    ("Testni tahrirlash", "Edit test"),
    ("Test tahriri", "Test edit"),
    ("Test natijalari", "Test results"),
    ("Boshlanish sanasi", "Start date"),
    ("Tugash sanasi", "End date"),
    ("Dars jadvali", "Class schedule"),
    ("Yangi dars vaqti", "New class time"),
    ("Hafta kuni", "Day of week"),
    ("Davomatni belgilash →", "Mark attendance →"),
    ("Ko'rish →", "View →"),
    ("Yangi Passage qo'shish", "Add new passage"),
    ("Yangi Qism (Part) qo'shish", "Add new part"),
    ("Yangi Task qo'shish", "Add new task"),
    ("Yangi qism qo'shish", "Add new part"),
    ("Yangi Part qo'shish", "Add new part"),
    ("Bo'lim ko'rsatmasi (instructions)", "Section instructions"),
    ("Bo'lim ko'rsatmasi", "Section instructions"),
    ("Qo'shimcha talablar (ixtiyoriy)", "Additional requirements (optional)"),
    ("Topshiriq matni *", "Task text *"),
    ("Topshiriq sharti", "Task prompt"),
    ("Sarlavha *", "Title *"),
    ("Part sarlavhasi", "Part title"),
    ("Passage sarlavhasi", "Passage title"),
    ("Section yaratish", "Create section"),
    ("Part yaratish", "Create part"),
    ("Task yaratish", "Create task"),
    ("Saqlanmoqda…", "Saving…"),
    ("Saqlanyapti…", "Saving…"),
    ("Saqlashda xatolik", "Save failed"),
    ("Yaratilmoqda…", "Creating…"),
    ("Yuklanmoqda…", "Loading…"),
    ("Yuborilmoqda…", "Submitting…"),
    ("Yuklashda xatolik", "Upload failed"),
    ("O'chirib bo'lmadi", "Couldn't delete"),
    ("O'chirishda xatolik", "Delete failed"),
    ("Excel yuklab bo'lmadi", "Couldn't download Excel"),
    ("Qayta urinishni boshlab bo'lmadi", "Couldn't start a retry"),
    ("Logo yuklandi", "Logo uploaded"),
    ("Audio yuklash", "Upload audio"),
    ("Audio yuklandi", "Audio uploaded"),
    ("Rasm yuklash", "Upload image"),
    ("Rasm yuklandi", "Image uploaded"),
    ("Rasm yuklanmadi", "Image failed to upload"),
    ("Rasm tanlash", "Choose image"),
    ("Boshqa fayl yuklash", "Upload another file"),
    ("Fayl tanlash", "Choose file"),
    ("Audio fayl", "Audio file"),
    ("Audio + saqlash", "Audio + save"),
    ("PDF yuklash", "Upload PDF"),
    ("Klon qilish", "Clone"),
    ("Plan saqlandi", "Plan saved"),
    ("Planni tahrirlash", "Edit plan"),
    ("Yangi plan", "New plan"),
    ("Narxlar saqlandi", "Prices saved"),
    ("Narxlarni saqlash", "Save prices"),
    ("Sozlamalar saqlandi", "Settings saved"),
    ("Baholashni saqlash", "Save grading"),
    ("Markaz tanlanmagan", "No center selected"),
    ("Bu oydagi daromad", "This month's revenue"),
    ("Bu oy attempts", "This month's attempts"),
    ("Tugatilgan sessiyalar", "Completed sessions"),
    ("Tugatilgan testlar", "Completed tests"),
    ("Mock sessiyalar", "Mock sessions"),
    ("Mock natijalar", "Mock results"),
    ("Test natijalari", "Test results"),
    ("Jami sessiyalar", "Total sessions"),
    ("Jami urinishlar", "Total attempts"),
    ("Jami fayllar", "Total files"),
    ("Jami tushum", "Total revenue"),
    ("Jami savollar", "Total questions"),
    ("Umumiy davomiylik", "Total duration"),
    ("Umumiy hajm", "Total size"),
    ("O'rtacha davomat", "Average attendance"),
    ("Barcha qiyinliklar", "All difficulties"),
    ("Barcha modullar", "All modules"),
    ("Barcha modul", "All modules"),
    ("Barcha holat", "All statuses"),
    ("Ustoz paneliga qaytish", "Back to teacher panel"),
    ("Markaz paneliga qaytish", "Back to center panel"),
    ("Bosh sahifa", "Home"),
    ("Javobni kiriting", "Enter your answer"),
    ("(javob berilmagan)", "(no answer)"),
    ("Test boshlash", "Start test"),
    ("Talaba qo'shish", "Add student"),
    ("Yangi mock sessiya", "New mock session"),
    ("Tezkor amallar", "Quick actions"),
    ("Haftalik aktivlik", "Weekly activity"),
    ("Yangi talaba", "New student"),
    ("Yangi ustoz", "New teacher"),
    ("Yangi test", "New test"),
    ("Klonlash…", "Cloning…"),
    ("Allaqachon nusxalangan", "Already cloned"),
    ("Markaz logosi", "Center logo"),
    ("Markaz nomi", "Center name"),
    ("Markaz testlari", "Center tests"),
    ("Asosiy rang", "Primary color"),
    ("Davomat tizimi ishlab chiqilmoqda. Bu bo'limda talabalar davomatini",
     "Attendance system is in development. This section will let you track student attendance"),
    ("Har kunlik davomat olish", "Daily attendance tracking"),
    ("QR kod orqali tezkor davomat", "Quick attendance via QR code"),
    ("Davomatni export qilish (Excel)", "Export attendance (Excel)"),
    ("Davomat statistikasi", "Attendance statistics"),
    ("Tez orada", "Coming soon"),
    ("Hisobot yuklanmadi.", "Couldn't load report."),
    ("Eng yaxshi", "Best"),
    ("Speaking modul tez kunda", "Speaking module coming soon"),
    ("To'g'ri javob: ", "Correct answer: "),
    ("To'g'ri javob:", "Correct answer:"),
    ("To'g'ri javob", "Correct answer"),
    ("Talaba uchun izoh (ixtiyoriy)", "Note for student (optional)"),
    ("Talaba javobi", "Student response"),
    ("To'g'ri/Jami", "Correct/Total"),
    ("To'g'ri javob (kichik harflarda yozing)", "Correct answer (in lowercase)"),
    ("Yangisini yuklash uchun ", "Upload a new one "),
    ("⊘ bekor qilingan", "⊘ revoked"),
    ("bekor qilingan", "revoked"),
    ("Pro markaz", "Pro center"),
    ("Hozirgi narx", "Current price"),
    ("Narx (USD)", "Price (USD)"),
    ("Narx ($)", "Price ($)"),
    ("Talabalar (-1 = ∞)", "Students (-1 = ∞)"),
    ("Ustozlar (-1 = ∞)", "Teachers (-1 = ∞)"),
    ("Davomiyligi (daqiqa)", "Duration (minutes)"),
    ("Davomiyligi (min)", "Duration (min)"),
    ("Davomiylik (kun)", "Duration (days)"),
    ("0–100 sessiya", "0–100 sessions"),
    ("101–500 sessiya", "101–500 sessions"),
    ("501+ sessiya", "501+ sessions"),
    ("E'lon qilish ✓", "Publish ✓"),
    ("E'lon qilish", "Publish"),
    ("Test nomi *", "Test name *"),
    ("Test nomi", "Test name"),
    ("Guruh nomi *", "Group name *"),
    ("Sertifikat:", "Certificate:"),
    ("Sessiya:", "Session:"),
    ("Talaba:", "Student:"),
    ("Markaz:", "Center:"),
    ("Ustoz:", "Teacher:"),
    ("javob...", "answer..."),
    ("✅ Nusxa yaratildi", "✅ Clone created"),
    ("— Tanlang —", "— Select —"),
    ("Yangi:", "New:"),
    ("o'chirilgan", "deleted"),
    ("O'chirilgan", "Deleted"),

    # Cleanups & late-discovered phrases
    ("Bekor qilish", "Cancel"),
    ("Cancel qilish", "Cancel"),
    ("Davom etish", "Continue"),
    ("Nashr qilish", "Publish"),
    ("Parse qilish", "Parse"),
    ("Savollar bo'yicha tahlil", "Question analysis"),
    ("Ma'lumot yo'q", "No data"),
    ("Ma'lumotlarni yuklab bo'lmadi.", "Couldn't load data."),
    ("Ma'lumot", "Information"),
    ("Bu guruhda talaba yo'q", "No students in this group"),
    ("bilan natija ko'rinadi.", "to see the result."),
    ("qoling, talabaga bering.", "and give it to the student."),
    ("Eslab qoling, talabaga bering.", "Remember it and give it to the student."),
    (" talaba\n", " students\n"),
    ("{c.total_students} talaba", "{c.total_students} students"),
    ("{o.days_remaining} kun", "{o.days_remaining} days"),
    ("{p.duration_days} kun", "{p.duration_days} days"),
    ("jami {o.sessions_total}", "total {o.sessions_total}"),
    # Cleanup of botched substring replacements from earlier iterations
    ("Informationlarni yuklab bo'lmadi.", "Couldn't load data."),
    ("Informationlarni yuklab bo‘lmadi.", "Couldn't load data."),

    # ── Backend: error / permission messages ────────────────────────────
    ("Login yoki parol noto'g'ri", "Invalid username or password"),
    ("vaqtincha o'chirib qo'yilgan. Markazga murojaat qiling.",
     "temporarily disabled. Please contact your center."),
    ("Bu test uchun ro'yxatdan o'tish kerak.",
     "Registration is required for this test."),
    ("Result hali hisoblanmagan", "Result not yet calculated"),
    ("Bu talaba sizning shogirdingiz emas.", "This student is not your apprentice."),
    ("Center faol holatda emas.", "Center is not active."),
    ("Faqat guruh o'qituvchisi yoki admin.", "Only the group teacher or admin."),
    ("Faqat admin yoki guruh o'qituvchisi.", "Only the admin or group teacher."),
    ("Faqat admin jadval yarata oladi.", "Only an admin can create a schedule."),
    ("Faqat admin tahrirlay oladi.", "Only an admin can edit."),
    ("Faqat admin o'chira oladi.", "Only an admin can delete."),
    ("Faqat o'z guruh talabangiz.", "Only students in your own group."),
    ("Faqat markaz admini guruh yarata oladi.",
     "Only the center admin can create a group."),
    ("Faqat admin talaba qo'sha oladi.", "Only an admin can add students."),
    ("Faqat admin talabani guruhdan chiqara oladi.",
     "Only an admin can remove a student from the group."),
    ("Yakunlangan sessiyani o'chirib bo'lmaydi.",
     "Cannot delete a finished session."),
    ("Session yakunlangan.", "Session has ended."),
    ("Allaqachon yakunlangan.", "Already ended."),
    ("Tugash vaqti boshlanish vaqtidan kech bo'lishi kerak.",
     "End time must be later than start time."),
    ("student_ids array bo'lishi kerak.", "student_ids must be an array."),
    ("Student bu guruhda emas.", "Student is not in this group."),
    ("O'chirildi.", "Deleted."),
    ("Student o'chirildi (deactivated).", "Student deleted (deactivated)."),
    ("Student qayta faollashtirildi.", "Student reactivated."),
    ("Teacher o'chirildi (deactivated).", "Teacher deleted (deactivated)."),
    ("Teacher topilmadi yoki shu markazda emas",
     "Teacher not found or not in this center"),
    ("Test draft holatiga qaytarildi", "Test moved back to draft"),
    ("Test qaytarildi.", "Test restored."),
    ("Avval testni arxivga o'tkazing, keyin doimiy o'chirib bo'ladi.",
     "Archive the test first, then it can be permanently deleted."),
    ("Global testni markazdan tahrirlab bo'lmaydi.",
     "Global tests cannot be edited from the center."),
    ("PDF 20 MB dan oshmasligi kerak.", "PDF must not exceed 20 MB."),
    ("Access code yaratib bo'lmadi, qayta urinib ko'ring.",
     "Couldn't create access code, please try again."),
    ("Score raqam bo'lishi kerak.", "Score must be a number."),
    ("Score 0–9 oralig'ida bo'lishi kerak.",
     "Score must be between 0 and 9."),
    ("Bu plan markazlarga biriktirilgan, o'chirib bo'lmaydi.",
     "This plan is assigned to centers and cannot be deleted."),
    ("Center topilmadi.", "Center not found."),
    ("Center faol emas. Administratorga murojaat qiling.",
     "Center is not active. Please contact the administrator."),
    ("Faqat Listening testlarga part qo'shish mumkin",
     "Parts can only be added to Listening tests"),
    ("Faqat Reading testlarga passage qo'shish mumkin",
     "Passages can only be added to Reading tests"),
    ("Faqat Writing testlarga task qo'shish mumkin",
     "Tasks can only be added to Writing tests"),
    ("Audio file yuklang", "Upload an audio file"),
    ("Chart rasm faqat Task 1 uchun", "Chart image is for Task 1 only"),
    ("Rasm yuklang", "Upload an image"),
    ("raqam bo'lishi kerak.", "must be a number."),

    # ── Backend: model verbose_name / help_text ──────────────────────────
    ("Dars jadvali", "Class schedule"),
    ("Dars jadvallari", "Class schedules"),
    ("Attendance sessiyasi", "Attendance session"),
    ("Attendance sessiyalari", "Attendance sessions"),
    ("Davomat yozuvi", "Attendance record"),
    ("Davomat yozuvlari", "Attendance records"),
    ("Davomat sessiyasi", "Attendance session"),
    ("Davomat sessiyalari", "Attendance sessions"),
    ("Misol: Room 301, Online", "e.g. Room 301, Online"),
    ("Misol: IELTS 7.0, Group A, Beginner 1",
     "e.g. IELTS 7.0, Group A, Beginner 1"),
    ("Qaysi jadvaldan yaratilgan (auto-generation paytida)",
     "Which schedule it was generated from (during auto-generation)"),
    ("Yakunlangandan keyin yozuvlarni o'zgartirib bo'lmaydi",
     "Records cannot be modified after the session ends"),
    ("Kechikish/kasal sababi va boshqalar",
     "Reason for tardiness/absence, etc."),
    ("Oylik obuna narxi (pay_per_test uchun 0)",
     "Monthly subscription price (0 for pay_per_test)"),
    ("Oyda nechta mock test (NULL = cheksiz)",
     "How many mock tests per month (NULL = unlimited)"),
    ("Progressiv narx chegarasi (umumiy hisoblangan testlar)",
     "Progressive pricing threshold (total billed tests)"),
    ("Threshold ichidagi har test narxi",
     "Per-test price under the threshold"),
    ("Threshold dan keyingi har test narxi",
     "Per-test price above the threshold"),
    ("0–100 sessions: bitta sessiya narxi (so'm)",
     "0–100 sessions: price per session (UZS)"),
    ("101–500 sessions: bitta sessiya narxi",
     "101–500 sessions: price per session"),
    ("501+ sessions: bitta sessiya narxi",
     "501+ sessions: price per session"),
    ("Bu davrda yakunlangan mock sessiyalar (charge yaratilgan)",
     "Mock sessions completed in this period (charges generated)"),
    ("Charge qilingan unique talabalar soni",
     "Number of unique students charged"),
    ("False — bepul/test sessiya, billing'da hisoblanmaydi",
     "False — free/test session, not counted in billing"),
    ("Speaking test (ixtiyoriy — mavjud bo'lsa speaking bosqichi qo'shiladi)",
     "Speaking test (optional — adds the speaking stage if present)"),
    ("Linkning amal qilish muddati (bo'sh bo'lsa cheksiz)",
     "Link expiration time (empty = unlimited)"),
    ("Session boshlangandan keyin ham qo'shilishga ruxsat",
     "Allow joining after the session starts"),
    ("Ro'yxatda yo'q talabalar ham ism kiritib qo'shilsinmi",
     "Whether students not on the roster can join by entering their name"),
    ("Login qilingan talaba bo'lsa unga link",
     "Direct link if the student is logged in"),
    ("Student yozib olgan speaking audio (webm/mp3/m4a)",
     "Speaking audio recorded by the student (webm/mp3/m4a)"),
    ("IELTS Overall: (L+R+W+S)/4, 0.5 stepda yaxlitlanadi",
     "IELTS Overall: (L+R+W+S)/4, rounded to 0.5"),
    ("Certificate berilgan mock participant",
     "Mock participant the certificate was issued to"),
    ("ORG-YYYY-MM-NNN formatida (e.g. ILDIZ-2026-05-001)",
     "Format: ORG-YYYY-MM-NNN (e.g. ILDIZ-2026-05-001)"),
    ("QR/URL orqali tekshirish uchun token",
     "Token for verification via QR or URL"),
    ("-1 = cheksiz", "-1 = unlimited"),
    ("Maqsad band score (6.5, 7.0, 7.5...)",
     "Target band score (6.5, 7.0, 7.5...)"),
    ("Null = superadmin global test (hamma markazlar uchun)",
     "Null = superadmin global test (for all centers)"),
    ("Asl global test (agar bu klon bo'lsa)",
     "Original global test (if this is a clone)"),
    ("Asl global test", "Original global test"),
    ("Klon test (markaz bazasidagi nusxa)",
     "Clone test (a copy in the center's database)"),
    ("Students mustaqil mashq qilish uchun bu testni ko'rsatishimi?",
     "Should this test be visible to students for independent practice?"),
    ("Practice rejimi vaqt limiti (daqiqada). Bo'sh — limit yo'q.",
     "Practice mode time limit (minutes). Empty = no limit."),
    ("Passage uchun rasm/diagram (ixtiyoriy)",
     "Image/diagram for the passage (optional)"),
    ("Test ichidagi tartib raqam (1-40)", "Order number within the test (1-40)"),
    ("Savol matni (yangi format)", "Question text (new format)"),
    ("Muqobil to'g'ri javoblar (yangi format)",
     "Alternate correct answers (new format)"),
    ("Savol uchun rasm (map, diagram, chart) — ixtiyoriy",
     "Image for the question (map, diagram, chart) — optional"),
    ("1, 2, 3 yoki 4", "1, 2, 3 or 4"),
    ("Bo'lim uchun rasm (ixtiyoriy)", "Image for the section (optional)"),
    ("1 yoki 2", "1 or 2"),
    ("Topshiriq matni", "Task text"),
    ("Faqat Task 1 uchun (chart, grafik, jadval rasmi)",
     "Only for Task 1 (chart, graph, table image)"),
    ("Qo'shimcha talablar (masalan: \"Compare both views\")",
     "Additional requirements (e.g. \"Compare both views\")"),

    # ── Backend: management command output ───────────────────────────────
    (" sessiya yaratildi (", " sessions generated ("),
    (" kun ichida)", " days)"),
    (" ta sessiya yaratildi", " sessions generated"),
    (" ta invoice yaratildi", " invoices generated"),
    ("=== Total ", "=== Total "),  # already English
    ("+30 kun", "+30 days"),
    ("+60 kun", "+60 days"),
    ("+", "+"),  # noop
    ("Necha kun oldinga (default: 30)", "How many days ahead (default: 30)"),
    ("ETAP 16 — oylik invoice'larni generatsiya qilish.",
     "ETAP 16 — generate monthly invoices."),
    ("ETAP 16 — oylik invoice generatsiya (har markaz uchun BillingCycle).",
     "ETAP 16 — monthly invoice generation (a BillingCycle per center)."),
    (" sessiya · ", " sessions · "),
    (" talaba · ", " students · "),

    # ── Backend: detail responses ────────────────────────────────────────
    ("Center tarif limiti to'ldi", "Center plan limit reached"),
    (" ta talaba). ", " students). "),
    (" ta talaba)", " students)"),
]


# ── Phase B: word-boundary single-token replacements ────────────────────
# These replace ONLY when the Uzbek word stands as a separate word (Latin
# letter boundary). They will not match when the word is part of a longer
# inflected form (e.g. "Talabalar", "Markazda").
# Each entry: (uzbek_word, english_word). Uzbek word should have no inflection.
WORDS: list[tuple[str, str]] = [
    ("Tasdiqlash", "Confirm"),
    ("Sessiyalar", "Sessions"),
    ("Sessiya", "Session"),
    ("Talabalar", "Students"),
    ("Talaba", "Student"),
    ("Ustozlar", "Teachers"),
    ("Ustoz", "Teacher"),
    ("Tahrirlash", "Edit"),
    ("Saqlash", "Save"),
    ("Davomat", "Attendance"),
    ("Sozlamalar", "Settings"),
    ("Holat", "Status"),
    ("Qiyinlik", "Difficulty"),
    ("Guruhlar", "Groups"),
    ("Guruh", "Group"),
    ("Nomi", "Name"),
    ("Sarlavha", "Title"),
    ("Natijalar", "Results"),
    ("Natija", "Result"),
    ("Hisobot", "Report"),
    ("Jadval", "Schedule"),
    ("Jami", "Total"),
    ("Sana", "Date"),
    ("Tarix", "History"),
    ("Boshqaruv", "Control"),
    ("Nofaol", "Inactive"),
    ("Faol", "Active"),
    ("Past", "Low"),
    ("Daromad", "Revenue"),
    ("Yangi", "New"),
    ("Bugungi", "Today's"),
    ("Yuborish", "Submit"),
    ("Almashtirish", "Replace"),
    ("Tanlang", "Select"),
    ("Sertifikat", "Certificate"),
    ("Plan", "Plan"),  # no-op placeholder; harmless
    ("O'chirish", "Delete"),
    ("Bekor", "Cancel"),
    ("Plans", "Plans"),  # no-op
    ("Markaz", "Center"),
    ("Markazlar", "Centers"),
    ("O'qituvchi", "Teacher"),
    ("O'quvchilar", "Students"),
]


# Apostrophe class used inside compiled patterns. Matches any single
# apostrophe glyph OR the two-character escape sequence \'.
APOST_CLASS = r"(?:\\'|['’‘ʻ])"


def build_phrase_regex(uz: str) -> re.Pattern[str]:
    """Build a regex that matches `uz` with any apostrophe glyph variant."""
    parts = [re.escape(seg) for seg in uz.split("'")]
    return re.compile(APOST_CLASS.join(parts))


# Sort by length descending so longer phrases match first
PHRASES_SORTED = sorted(PHRASES, key=lambda p: len(p[0]), reverse=True)
PHRASE_REGEXES: list[tuple[re.Pattern[str], str]] = [
    (build_phrase_regex(uz), en) for uz, en in PHRASES_SORTED
]


# Word-boundary regex: word must be preceded by a non-letter and followed
# by a non-letter. Apostrophes are NOT in the boundary set.
_LETTER = r"A-Za-zА-Яа-я"


def build_word_regex(word: str) -> re.Pattern[str]:
    parts = [re.escape(seg) for seg in word.split("'")]
    body = APOST_CLASS.join(parts)
    return re.compile(rf"(?<![{_LETTER}]){body}(?![{_LETTER}])")


WORDS_SORTED = sorted(WORDS, key=lambda p: len(p[0]), reverse=True)
WORD_REGEXES: list[tuple[re.Pattern[str], str]] = [
    (build_word_regex(uz), en) for uz, en in WORDS_SORTED
]


def apply(text: str) -> tuple[int, str]:
    n = 0
    # Phase A — multi-word phrase regexes (apostrophe-tolerant)
    for rx, en in PHRASE_REGEXES:
        # Use a callable replacement to escape backreferences in `en`
        new_text, count = rx.subn(lambda _m, e=en: e, text)
        if count:
            text = new_text
            n += count
    # Phase B — word-boundary single tokens
    for rx, en in WORD_REGEXES:
        new_text, count = rx.subn(lambda _m, e=en: e, text)
        if count:
            text = new_text
            n += count
    return n, text


def main() -> None:
    total_files = 0
    total_repl = 0
    for root in (FRONTEND, BACKEND):
        if not root.exists():
            continue
        for f in root.rglob("*"):
            if not f.is_file():
                continue
            if f.suffix not in {".tsx", ".ts", ".jsx", ".js", ".py"}:
                continue
            parts = set(f.parts)
            if "migrations" in parts or "__pycache__" in parts:
                continue
            if ".venv" in parts or "venv" in parts or "node_modules" in parts:
                continue
            try:
                original = f.read_text(encoding="utf-8")
            except Exception:
                continue
            n, new = apply(original)
            if n > 0:
                f.write_text(new, encoding="utf-8")
                total_files += 1
                total_repl += n
                print(f"  {n:3} replacements in {f.relative_to(ROOT)}")
    print(f"\nFiles modified: {total_files} | Total replacements: {total_repl}")


if __name__ == "__main__":
    main()
