# Generated by Django 5.1.15 on 2026-04-27 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmembership'),
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alt_answers',
            field=models.JSONField(blank=True, default=list, help_text='Muqobil to‘g‘ri javoblar (yangi format)'),
        ),
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text='Savol matni (yangi format)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Test ichidagi tartib raqam (1-40)'),
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g. "Cambridge IELTS 19"', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Asl global test (agar bu klon bo‘lsa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='tests.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.passage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tfng', 'True/False/Not Given'), ('ynng', 'Yes/No/Not Given'), ('fill', 'Fill in the Blank'), ('gap_fill', 'Gap Fill'), ('matching', 'Matching'), ('short_answer', 'Short Answer'), ('form_completion', 'Form Completion'), ('map_labeling', 'Map Labeling'), ('summary_completion', 'Summary Completion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Boshlang‘ich (4.5–5.5)'), ('intermediate', 'O‘rta (5.5–6.5)'), ('advanced', 'Yuqori (6.5–7.5)'), ('expert', 'Mahoratli (7.5+)'), ('easy', 'Easy (5.0–6.0)'), ('medium', 'Medium (6.0–7.0)'), ('hard', 'Hard (7.0–8.5)')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='module',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('full_mock', 'Full Mock (L+R+W)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ListeningPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveSmallIntegerField(help_text='1, 2, 3 yoki 4')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='listening_audio/')),
                ('audio_duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio_bitrate_kbps', models.PositiveIntegerField(default=0)),
                ('audio_size_bytes', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='', help_text='Bo‘lim ko‘rsatmasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_parts', to='tests.test')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('test', 'part_number')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='listening_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.listeningpart'),
        ),
        migrations.CreateModel(
            name='TestClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cloned_test', models.ForeignKey(help_text='Klon test (markaz bazasidagi nusxa)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tests.test')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_clones', to='organizations.organization')),
                ('source_test', models.ForeignKey(help_text='Asl global test', on_delete=django.db.models.deletion.CASCADE, related_name='clone_records', to='tests.test')),
            ],
            options={
                'ordering': ['-cloned_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveSmallIntegerField(help_text='1 yoki 2')),
                ('prompt', models.TextField(help_text='Topshiriq matni')),
                ('chart_image', models.ImageField(blank=True, help_text='Faqat Task 1 uchun (chart, grafik, jadval rasmi)', null=True, upload_to='writing_charts/')),
                ('min_words', models.PositiveIntegerField(default=150)),
                ('suggested_minutes', models.PositiveIntegerField(default=20)),
                ('requirements', models.TextField(blank=True, default='', help_text='Qo‘shimcha talablar (masalan: "Compare both views")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='tests.test')),
            ],
            options={
                'ordering': ['task_number'],
                'unique_together': {('test', 'task_number')},
            },
        ),
    ]
