# Generated by Django 5.1.15 on 2026-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='min_words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
