# Generated by Django 5.1.15 on 2026-04-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_passage_min_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Boshlang‘ich (4.5–5.5)'), ('intermediate', 'O‘rta (5.5–6.5)'), ('advanced', 'Yuqori (6.5–7.5)'), ('expert', 'Mahoratli (7.5+)')], default='medium', max_length=20),
        ),
    ]
