# Generated by Django 5.1.15 on 2026-04-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tests', '0003_alter_test_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null = superadmin global test (hamma markazlar uchun)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='organizations.organization'),
        ),
    ]
