# Generated by Django 5.1.15 on 2026-04-27 20:11

import apps.tests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_passage_instructions_passage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningpart',
            name='image',
            field=models.ImageField(blank=True, help_text='Bo‘lim uchun rasm (ixtiyoriy)', null=True, upload_to='listening_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='passage',
            name='image',
            field=models.ImageField(blank=True, help_text='Passage uchun rasm/diagram (ixtiyoriy)', null=True, upload_to='passage_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Savol uchun rasm (map, diagram, chart) — ixtiyoriy', null=True, upload_to='question_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='listeningpart',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening_audio/%Y/%m/', validators=[apps.tests.validators.validate_audio_file]),
        ),
    ]
