# Generated by Django 5.1.15 on 2026-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_listeningpart_image_passage_image_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_practice_enabled',
            field=models.BooleanField(default=False, help_text='Talabalar mustaqil mashq qilish uchun bu testni ko‘rsatishimi?'),
        ),
        migrations.AddField(
            model_name='test',
            name='practice_time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Practice rejimi vaqt limiti (daqiqada). Bo‘sh — limit yo‘q.', null=True),
        ),
    ]
