# Generated by Django 5.1.15 on 2026-05-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_status_alter_plan_max_students_and_more'),
        ('tests', '0007_question_type_matching_headings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpart',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the section (optional)', null=True, upload_to='listening_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='listeningpart',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Section instructions'),
        ),
        migrations.AlterField(
            model_name='listeningpart',
            name='part_number',
            field=models.PositiveSmallIntegerField(help_text='1, 2, 3 or 4'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image/diagram for the passage (optional)', null=True, upload_to='passage_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alt_answers',
            field=models.JSONField(blank=True, default=list, help_text='Alternate correct answers (new format)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the question (map, diagram, chart) — optional', null=True, upload_to='question_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text='Question text (new format)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order number within the test (1-40)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi_choice', 'Multiple Choice (Multi-Select)'), ('tfng', 'True/False/Not Given'), ('ynng', 'Yes/No/Not Given'), ('fill', 'Fill in the Blank'), ('gap_fill', 'Gap Fill'), ('matching', 'Matching'), ('matching_headings', 'Matching Headings'), ('short_answer', 'Short Answer'), ('form_completion', 'Form Completion'), ('map_labeling', 'Map Labeling'), ('summary_completion', 'Summary Completion'), ('sentence_completion', 'Sentence Completion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Original global test (if this is a clone)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_practice_enabled',
            field=models.BooleanField(default=False, help_text='Should this test be visible to students for independent practice?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null = superadmin global test (for all centers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='test',
            name='practice_time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Practice mode time limit (minutes). Empty = no limit.', null=True),
        ),
        migrations.AlterField(
            model_name='testclone',
            name='cloned_test',
            field=models.ForeignKey(help_text="Clone test (a copy in the center's database)", on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='testclone',
            name='source_test',
            field=models.ForeignKey(help_text='Original global test', on_delete=django.db.models.deletion.CASCADE, related_name='clone_records', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='chart_image',
            field=models.ImageField(blank=True, help_text='Only for Task 1 (chart, graph, table image)', null=True, upload_to='writing_charts/'),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='prompt',
            field=models.TextField(help_text='Task text'),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Additional requirements (e.g. "Compare both views")'),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='task_number',
            field=models.PositiveSmallIntegerField(help_text='1 or 2'),
        ),
    ]
