# Generated by Django 5.1.15 on 2026-05-05 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_status_alter_plan_max_students_and_more'),
        ('tests', '0008_alter_listeningpart_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('pdf_file', models.FileField(upload_to='test_pdfs/')),
                ('audio_part1', models.FileField(blank=True, null=True, upload_to='listening_audios/')),
                ('audio_part2', models.FileField(blank=True, null=True, upload_to='listening_audios/')),
                ('audio_part3', models.FileField(blank=True, null=True, upload_to='listening_audios/')),
                ('audio_part4', models.FileField(blank=True, null=True, upload_to='listening_audios/')),
                ('answer_key', models.JSONField()),
                ('total_questions', models.IntegerField(default=40)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_tests_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_tests', to='organizations.organization')),
            ],
            options={
                'db_table': 'tests_pdftest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('total_questions', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('results', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_test_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.pdftest')),
            ],
            options={
                'db_table': 'tests_pdfattempt',
                'ordering': ['-started_at'],
            },
        ),
    ]
