# Generated by Django 5.1.15 on 2026-05-08 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_pdftest_public_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pdftestattempt',
            new_name='tests_pdfat_test_id_b65dd8_idx',
            old_name='tests_pdfat_test_id_student_idx',
        ),
        migrations.AlterField(
            model_name='pdftest',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='URLs use this UUID instead of the sequential int PK.', unique=True),
        ),
    ]
