# Generated by Django 5.1.15 on 2026-05-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_rename_tests_pdfat_test_id_student_idx_tests_pdfat_test_id_b65dd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
