# Generated by Django 5.1.15 on 2026-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_add_question_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftest',
            name='pdf_page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdftest',
            name='pdf_pages',
            field=models.JSONField(blank=True, default=list, help_text="Aylantirilgan PNG sahifalarning media URL'lari (masalan ['/media/pdf_pages/<uuid>/page_1.png', ...])"),
        ),
    ]
