# Generated by Django 5.1.15 on 2026-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_pdftest_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text="Parser tomonidan generatsiya qilingan HTML. To'g'ridan-to'g'ri tahrir qilmang."),
        ),
        migrations.AddField(
            model_name='passage',
            name='content_source',
            field=models.TextField(blank=True, default='', help_text='HTML DSL manba matni (admin tahrir qiladi). {1}, {2} markerlar.'),
        ),
    ]
