# Generated by Django 5.1.15 on 2026-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_passage_content_html_passage_content_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_for_b2c',
            field=models.BooleanField(db_index=True, default=False, help_text="B2C katalogida ko'rinishi uchun belgilang."),
        ),
        migrations.AddField(
            model_name='test',
            name='b2c_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='b2c_display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='test',
            name='b2c_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
