# Generated by Django 5.1.15 on 2026-05-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_test_strict_mode_enabled_and_more'),
        ('tests', '0017_test_source_test_source_custom_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('use_ai', models.BooleanField(default=False)),
                ('section_type_hint', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Davom etmoqda'), ('ai_parsed', 'AI parse qildi'), ('saved', 'Test saqlandi'), ('failed', 'Xato'), ('completed_no_ai', 'AI ishlatilmadi')], default='processing', max_length=20)),
                ('provider_name', models.CharField(blank=True, default='', max_length=50)),
                ('model_used', models.CharField(blank=True, default='', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_imports', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF import log',
                'verbose_name_plural': 'PDF import logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
