# Generated by Django 5.1.15 on 2026-05-11 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_pdfimportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini_aistudio', 'Gemini AI Studio'), ('claude_anthropic', 'Claude (Anthropic)')], max_length=30, unique=True)),
                ('model_name', models.CharField(blank=True, default='', help_text='masalan: gemini-2.5-flash, claude-sonnet-4-6', max_length=100)),
                ('encrypted_api_key', models.TextField(blank=True, default='', help_text='Fernet bilan shifrlangan API key. Hech qachon plain matn emas.')),
                ('api_key_last4', models.CharField(blank=True, default='', help_text="UI da ko'rsatish uchun oxirgi 4 belgi (encrypted emas).", max_length=4)),
                ('is_active', models.BooleanField(default=False, help_text="True bo'lsa, get_ai_provider() shu provider'ni qaytaradi.")),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True, default='')),
                ('last_test_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Configs',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('key_set', "API key o'rnatildi"), ('key_updated', 'API key yangilandi'), ('key_cleared', "API key o'chirildi"), ('model_changed', "Model o'zgartirildi"), ('activated', 'Aktiv qilindi'), ('deactivated', 'Deaktiv qilindi'), ('test_connection', "Sinov o'tkazildi")], max_length=30)),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', max_length=200)),
                ('test_success', models.BooleanField(blank=True, null=True)),
                ('test_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tests.aiproviderconfig')),
            ],
            options={
                'verbose_name': 'AI provider audit log',
                'verbose_name_plural': 'AI provider audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
