# Generated by Django 5.1.15 on 2026-04-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (only superadmin sees)'),
        ),
    ]
