# Generated by Django 5.1.15 on 2026-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_studentgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Tarif tugagan'), ('blocked', 'Bloklangan')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_students',
            field=models.IntegerField(default=5, help_text='-1 = unlimited'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_teachers',
            field=models.IntegerField(default=1, help_text='-1 = unlimited'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(help_text='e.g. IELTS 7.0, Group A, Beginner 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='target_band_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Target band score (6.5, 7.0, 7.5...)', max_digits=3, null=True),
        ),
    ]
