# Generated by Django 5.1.15 on 2026-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_status_alter_plan_max_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='test_strict_mode_enabled',
            field=models.BooleanField(default=True, help_text="True bo'lsa, talabalar testda fullscreen + shortcut blocking ko'radi"),
        ),
        migrations.AddField(
            model_name='organization',
            name='test_violation_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text="N ta counted violation bo'lsa attempt avtomatik submit. 0 = auto-submit o'chiq"),
        ),
    ]
